export default [
  {
    id: 1,
    age: 20,
    gen: "مرد",
    email: "george.bluth@reqres.in",
    name: "طاها دلربا",
    avatar: "https://reqres.in/img/faces/1-image.jpg",
  },
  {
    id: 3,
    age: 19,
    gen: "زن",
    email: "emma.wong@reqres.in",
    name: "نسترن جمشیدی",
    avatar: "https://reqres.in/img/faces/3-image.jpg",
  },
  {
    id: 2,
    age: 32,
    gen: "مرد",
    email: "janet.weaver@reqres.in",
    name: "مهدی نجفی",
    avatar: "https://reqres.in/img/faces/2-image.jpg",
  },
  {
    id: 4,
    age: 18,
    gen: "مرد",
    email: "eve.holt@reqres.in",
    name: "محسن لطفی",
    avatar: "https://reqres.in/img/faces/4-image.jpg",
  },
  {
    id: 5,
    age: 24,
    gen: "مرد",
    email: "charles.morris@reqres.in",
    name: "ایمان رضایی",
    avatar: "https://reqres.in/img/faces/5-image.jpg",
  },
  {
    id: 6,
    age: 27,
    gen: "زن",
    email: "tracey.ramos@reqres.in",
    name: "آوا احمدی",
    avatar: "https://reqres.in/img/faces/6-image.jpg",
  },
  {
    id: 7,
    age: 34,
    gen: "مرد",
    email: "michael.lawson@reqres.in",
    name: "حسن شماعی زاده",
    avatar: "https://reqres.in/img/faces/7-image.jpg",
  },
  {
    id: 8,
    age: 17,
    gen: "مرد",
    email: "lindsay.ferguson@reqres.in",
    name: "شهرام شب پره",
    avatar: "https://reqres.in/img/faces/8-image.jpg",
  },
  {
    id: 9,
    age: 31,
    gen: "زن",
    email: "tobias.funke@reqres.in",
    name: "فاطمه حیدری",
    avatar: "https://reqres.in/img/faces/9-image.jpg",
  },
  {
    id: 10,
    age: 20,
    gen: "مرد",
    email: "byron.fields@reqres.in",
    name: "احمد لطیفی",
    avatar: "https://reqres.in/img/faces/10-image.jpg",
  },
  {
    id: 11,
    age: 29,
    gen: "مرد",
    email: "george.edwards@reqres.in",
    name: "عباس نوبخت",
    avatar: "https://reqres.in/img/faces/11-image.jpg",
  },
  {
    id: 12,
    age: 35,
    gen: "زن",
    email: "rachel.howell@reqres.in",
    name: "آزاده صمدی",
    avatar: "https://reqres.in/img/faces/12-image.jpg",
  },
];
